import React from "react";
import Head from "next/head";
import ContactList from '../components/ContactList';
import Link from 'next/link';
import styles from '../styles/ContactList.module.scss';




export default function Home() {
  // Your code here

  //Felt more comfortable separating code into different files for organization, see components folder

  return (
    <>
      <Head>
        <title>Frontend-test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="home">
        {/* Your code here */}
        <div> 
           <ContactList />
        </div>

        {/* ∆∆∆∆∆∆∆∆∆∆∆∆∆∆ */}
      </main>
    </>
  );
}
